name: CI Pipeline

# Define when the workflow should be triggered
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs to run as part of this workflow
jobs:
  test:
    # Specify the virtual environment to run the job on
    runs-on: ubuntu-latest

    # Define the steps to execute in the job
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Replace '3.x' with the specific Python version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      # Step 4: Run pylint for static code analysis
      - name: Run pylint
        run: |
          pylint life_expectancy.cleaning --pylint-config-file pyproject.toml

      # Step 5: Run pytest for unit tests
      - name: Run pytest
        run: |
          pytest --maxfail=5 --disable-warnings
